# Generated by Django 4.0.2 on 2022-02-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('RollNumber', models.CharField(max_length=30)),
                ('Class', models.CharField(max_length=30)),
                ('Image', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
